apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-springboot
  name: javaservice
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8000
  selector:
    app: java-springboot
  type: Nodeport
status:
  loadBalancer: {}
